project/master-degree-system/config/routes.rb
MasterDegreeSystem::Application.routes.draw do
  get "home/others"
  get "home/reports"
  get "home/index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, module: :devise
  

  resources :student_sci_degrees do
    resources :student_sci_degree_grades
  end

  resources :sci_degree_classes

  resources :student_program_giving_grades

  resources :student_scientific_degree_grades

  resources :user_privilege_group_roles

  resources :privilege_group_roles

  resources :privilege_groups

  resources :roles

  resources :student_scientific_degrees

  resources :departments

  resources :faculties

  resources :universities

  resources :scientific_degree_classes

  resources :student_program_warning_histories

  resources :student_program_status_histories

  resources :program_class_statuses

  resources :student_program_professors

  resources :grade_classes

  resources :student_programs do
    resources :student_program_courses
  end

  resources :students do
    collection do
      get :student_listing_no_report
      get :student_with_supervised
      get :old_student
    end
  end

  resources :professor_program_class_courses

  resources :professors

  resources :users

  resources :user_types

  resources :professor_titles

  resources :program_class_semester_courses

  resources :program_classes do
    collection do
      get :course_details
    end
  end

  resources :semesters

  resources :course_classes

  resources :courses

  get  'others' => 'home#others'
  root 'home#index'

  

end

project/master-degree-system/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/course_class.rb
class CourseClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/grade_class.rb
class GradeClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/privilege_group.rb
class PrivilegeGroup < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  belongs_to :professorTitle
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor_title.rb
class ProfessorTitle < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/program_class.rb
class ProgramClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student_program.rb
class StudentProgram < ActiveRecord::Base
  belongs_to :student
  belongs_to :ProgramClass
  belongs_to :semester
  has_many :studentProgramCourses, foreign_key: "studentProgram_id"
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :userType
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @professors = User.where(id: Professor.all.pluck(:user_id))
    respond_with(@professors)
  end

  def show
    respond_with(@professor)
  end

  def new
    @professor = Professor.new
    respond_with(@professor)
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)
    @professor.save
    respond_with(@professor)
  end

  def update
    @professor.update(professor_params)
    respond_with(@professor)
  end

  def destroy
    @professor.destroy
    respond_with(@professor)
  end

  private
    def set_professor
      @professor = Professor.find_by(user_id: params[:id])
    end

    def professor_params
      params.require(:professor).permit(:user_id, :professorTitle_id, :creator_id, :modifier_id)
    end
end

project/master-degree-system/app/helpers/courses_helper.rb
module CoursesHelper
end

project/master-degree-system/app/helpers/home_helper.rb
module HomeHelper
end

project/master-degree-system/app/helpers/professors_helper.rb
module ProfessorsHelper
end

project/master-degree-system/app/helpers/roles_helper.rb
module RolesHelper
end

project/master-degree-system/app/helpers/students_helper.rb
module StudentsHelper
end

project/master-degree-system/app/helpers/users_helper.rb
module UsersHelper
end

project/master-degree-system/app/views/professors/_form.html.haml
= form_for(@professor) do |f|
  - if @professor.errors.any?
    #error_explanation
      %h2
        = pluralize(@professor.errors.count, "error")
        prohibited this professor from being saved:
      %ul
        - @professor.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user
    %br/
    = f.text_field :user
  .field
    = f.label :professorTitle
    %br/
    = f.text_field :professorTitle
  .field
    = f.label :creator
    %br/
    = f.text_field :creator
  .field
    = f.label :modifier
    %br/
    = f.text_field :modifier
  .actions
    = f.submit

project/master-degree-system/app/views/professors/edit.html.haml
%h1 Editing professor
= render 'form'
= link_to 'Show', @professor
/ = link_to 'Back', professors_path

project/master-degree-system/app/views/professors/index.html.haml
%h1 Listing professors
%table.table
  %thead
    %tr
      %th National ID
      %th Name
      %th Mobilenumber
      %th Phonenumber
      %th Email
      %th
      %th
      %th
  %tbody
    - @professors.each do |professor|
      %tr
        %td= professor.nationalID
        %td= professor.name
        %td= professor.mobileNumber
        %td= professor.phoneNumber
        %td= professor.email
        %td= link_to 'Show', professor_path(professor)
        %td= link_to 'Edit', edit_user_path(professor)
        %td= link_to 'Delete', professor, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Professor', new_user_path

project/master-degree-system/app/views/professors/new.html.haml
%h1 New professor
= render 'form'
/ = link_to 'Back', professors_path

project/master-degree-system/app/views/professors/show.html.haml
%p
  %strong Professor Title:
  = @professor.professorTitle || "Prof."
 
%p
  %strong Name:
  = @professor.user.name

%h4 
  %strong Professors Reports
%p
  = link_to 'Show Student Has No Report', student_listing_no_report_students_path(professor_id: @professor.id)
%p
  = link_to 'Supervised Student', student_with_supervised_students_path(professor_id: @professor.id)

= link_to 'Edit', edit_professor_path(@professor)
/ = link_to 'Back', professors_path