project/master-degree-system/config/routes.rb
MasterDegreeSystem::Application.routes.draw do
  get "home/others"
  get "home/reports"
  get "home/index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, module: :devise
  

  resources :student_sci_degrees do
    resources :student_sci_degree_grades
  end

  resources :sci_degree_classes

  resources :student_program_giving_grades

  resources :student_scientific_degree_grades

  resources :user_privilege_group_roles

  resources :privilege_group_roles

  resources :privilege_groups

  resources :roles

  resources :student_scientific_degrees

  resources :departments

  resources :faculties

  resources :universities

  resources :scientific_degree_classes

  resources :student_program_warning_histories

  resources :student_program_status_histories

  resources :program_class_statuses

  resources :student_program_professors

  resources :grade_classes

  resources :student_programs do
    resources :student_program_courses
  end

  resources :students do
    collection do
      get :student_listing_no_report
      get :student_with_supervised
      get :old_student
    end
  end

  resources :professor_program_class_courses

  resources :professors

  resources :users

  resources :user_types

  resources :professor_titles

  resources :program_class_semester_courses

  resources :program_classes do
    collection do
      get :course_details
    end
  end

  resources :semesters

  resources :course_classes

  resources :courses

  get  'others' => 'home#others'
  root 'home#index'

  

end

project/master-degree-system/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/course_class.rb
class CourseClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/grade_class.rb
class GradeClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/privilege_group.rb
class PrivilegeGroup < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  belongs_to :professorTitle
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor_title.rb
class ProfessorTitle < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/program_class.rb
class ProgramClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student_program.rb
class StudentProgram < ActiveRecord::Base
  belongs_to :student
  belongs_to :ProgramClass
  belongs_to :semester
  has_many :studentProgramCourses, foreign_key: "studentProgram_id"
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :userType
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/controllers/program_class_statuses_controller.rb
class ProgramClassStatusesController < ApplicationController
  before_action :set_program_class_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @program_class_statuses = ProgramClassStatus.all
    respond_with(@program_class_statuses)
  end

  def show
    respond_with(@program_class_status)
  end

  def new
    @program_class_status = ProgramClassStatus.new
    respond_with(@program_class_status)
  end

  def edit
  end

  def create
    @program_class_status = ProgramClassStatus.new(program_class_status_params)
    @program_class_status.save
    respond_with(@program_class_status)
  end

  def update
    @program_class_status.update(program_class_status_params)
    respond_with(@program_class_status)
  end

  def destroy
    @program_class_status.destroy
    respond_with(@program_class_status)
  end

  private
    def set_program_class_status
      @program_class_status = ProgramClassStatus.find(params[:id])
    end

    def program_class_status_params
      params.require(:program_class_status).permit(:programClass_id, :preProgramClass_id, :status, :creator_id, :modifier_id)
    end
end

project/master-degree-system/app/helpers/courses_helper.rb
module CoursesHelper
end

project/master-degree-system/app/helpers/home_helper.rb
module HomeHelper
end

project/master-degree-system/app/helpers/program_class_statuses_helper.rb
module ProgramClassStatusesHelper
end

project/master-degree-system/app/helpers/roles_helper.rb
module RolesHelper
end

project/master-degree-system/app/helpers/users_helper.rb
module UsersHelper
end

project/master-degree-system/app/views/program_class_statuses/_form.html.haml
= form_for(@program_class_status) do |f|
  - if @program_class_status.errors.any?
    #error_explanation
      %h2
        = pluralize(@program_class_status.errors.count, "error")
        prohibited this program_class_status from being saved:
      %ul
        - @program_class_status.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :programClass
    %br/
    = f.text_field :programClass
  .field
    = f.label :preProgramClass
    %br/
    = f.text_field :preProgramClass
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .actions
    = f.submit

project/master-degree-system/app/views/program_class_statuses/edit.html.haml
%h1 Editing program_class_status
= render 'form'
= link_to 'Show', @program_class_status
/ = link_to 'Back', program_class_statuses_path

project/master-degree-system/app/views/program_class_statuses/index.html.haml
%h1 Program Class Statuses
%table.table
  %thead
    %tr
      %th Programclass
      %th Preprogramclass
      %th Status
      %th
      %th
      %th
  %tbody
    - @program_class_statuses.each do |program_class_status|
      %tr
        %td= program_class_status.programClass.name
        %td= program_class_status.preProgramClass.try(:name)
        %td= program_class_status.status
        %td= link_to 'Show', program_class_status
        %td= link_to 'Edit', edit_program_class_status_path(program_class_status)
        %td= link_to 'Delete', program_class_status, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Program class status', new_program_class_status_path

project/master-degree-system/app/views/program_class_statuses/new.html.haml
%h1 New program_class_status
= render 'form'
/ = link_to 'Back', program_class_statuses_path

project/master-degree-system/app/views/program_class_statuses/show.html.haml
 
%p
  %strong Programclass:
  = @program_class_status.programClass
%p
  %strong Preprogramclass:
  = @program_class_status.preProgramClass
%p
  %strong Status:
  = @program_class_status.status
%p
  %strong Creator:
  = @program_class_status.creator
%p
  %strong Modifier:
  = @program_class_status.modifier
= link_to 'Edit', edit_program_class_status_path(@program_class_status)
/ = link_to 'Back', program_class_statuses_path