project/master-degree-system/config/routes.rb
MasterDegreeSystem::Application.routes.draw do
  get "home/others"
  get "home/reports"
  get "home/index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, module: :devise
  

  resources :student_sci_degrees do
    resources :student_sci_degree_grades
  end

  resources :sci_degree_classes

  resources :student_program_giving_grades

  resources :student_scientific_degree_grades

  resources :user_privilege_group_roles

  resources :privilege_group_roles

  resources :privilege_groups

  resources :roles

  resources :student_scientific_degrees

  resources :departments

  resources :faculties

  resources :universities

  resources :scientific_degree_classes

  resources :student_program_warning_histories

  resources :student_program_status_histories

  resources :program_class_statuses

  resources :student_program_professors

  resources :grade_classes

  resources :student_programs do
    resources :student_program_courses
  end

  resources :students do
    collection do
      get :student_listing_no_report
      get :student_with_supervised
      get :old_student
    end
  end

  resources :professor_program_class_courses

  resources :professors

  resources :users

  resources :user_types

  resources :professor_titles

  resources :program_class_semester_courses

  resources :program_classes do
    collection do
      get :course_details
    end
  end

  resources :semesters

  resources :course_classes

  resources :courses

  get  'others' => 'home#others'
  root 'home#index'

  

end

project/master-degree-system/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/course_class.rb
class CourseClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/grade_class.rb
class GradeClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/privilege_group.rb
class PrivilegeGroup < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  belongs_to :professorTitle
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor_title.rb
class ProfessorTitle < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/program_class.rb
class ProgramClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student_program.rb
class StudentProgram < ActiveRecord::Base
  belongs_to :student
  belongs_to :ProgramClass
  belongs_to :semester
  has_many :studentProgramCourses, foreign_key: "studentProgram_id"
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :userType
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  before_action :set_user_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @user_types = UserType.all
    respond_with(@user_types)
  end

  def show
    respond_with(@user_type)
  end

  def new
    @user_type = UserType.new
    respond_with(@user_type)
  end

  def edit
  end

  def create
    @user_type = UserType.new(user_type_params)
    @user_type.save
    respond_with(@user_type)
  end

  def update
    @user_type.update(user_type_params)
    respond_with(@user_type)
  end

  def destroy
    @user_type.destroy
    respond_with(@user_type)
  end

  private
    def set_user_type
      @user_type = UserType.find(params[:id])
    end

    def user_type_params
      params.require(:user_type).permit(:name, :creator_id, :modifier_id)
    end
end

project/master-degree-system/app/helpers/courses_helper.rb
module CoursesHelper
end

project/master-degree-system/app/helpers/home_helper.rb
module HomeHelper
end

project/master-degree-system/app/helpers/roles_helper.rb
module RolesHelper
end

project/master-degree-system/app/helpers/user_types_helper.rb
module UserTypesHelper
end

project/master-degree-system/app/helpers/users_helper.rb
module UsersHelper
end

project/master-degree-system/app/views/user_types/_form.html.haml
= form_for(@user_type) do |f|
  - if @user_type.errors.any?
    #error_explanation
      %h2
        = pluralize(@user_type.errors.count, "error")
        prohibited this user_type from being saved:
      %ul
        - @user_type.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

project/master-degree-system/app/views/user_types/edit.html.haml
%h1 Editing user_type
= render 'form'
= link_to 'Show', @user_type
/ = link_to 'Back', user_types_path

project/master-degree-system/app/views/user_types/index.html.haml
%h1 User Types
%table.table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  %tbody
    - @user_types.each do |user_type|
      %tr
        %td= user_type.name
        %td= link_to 'Show', user_type
        %td= link_to 'Edit', edit_user_type_path(user_type)
        %td= link_to 'Delete', user_type, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User type', new_user_type_path

project/master-degree-system/app/views/user_types/new.html.haml
%h1 New user_type
= render 'form'
/ = link_to 'Back', user_types_path

project/master-degree-system/app/views/user_types/show.html.haml
 
%p
  %strong Name:
  = @user_type.name
%p
  %strong Creator:
  = @user_type.creator
%p
  %strong Modifier:
  = @user_type.modifier
= link_to 'Edit', edit_user_type_path(@user_type)
/ = link_to 'Back', user_types_path