project/master-degree-system/config/routes.rb
MasterDegreeSystem::Application.routes.draw do
  get "home/others"
  get "home/reports"
  get "home/index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, module: :devise
  

  resources :student_sci_degrees do
    resources :student_sci_degree_grades
  end

  resources :sci_degree_classes

  resources :student_program_giving_grades

  resources :student_scientific_degree_grades

  resources :user_privilege_group_roles

  resources :privilege_group_roles

  resources :privilege_groups

  resources :roles

  resources :student_scientific_degrees

  resources :departments

  resources :faculties

  resources :universities

  resources :scientific_degree_classes

  resources :student_program_warning_histories

  resources :student_program_status_histories

  resources :program_class_statuses

  resources :student_program_professors

  resources :grade_classes

  resources :student_programs do
    resources :student_program_courses
  end

  resources :students do
    collection do
      get :student_listing_no_report
      get :student_with_supervised
      get :old_student
    end
  end

  resources :professor_program_class_courses

  resources :professors

  resources :users

  resources :user_types

  resources :professor_titles

  resources :program_class_semester_courses

  resources :program_classes do
    collection do
      get :course_details
    end
  end

  resources :semesters

  resources :course_classes

  resources :courses

  get  'others' => 'home#others'
  root 'home#index'

  

end

project/master-degree-system/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/course_class.rb
class CourseClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/grade_class.rb
class GradeClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/privilege_group.rb
class PrivilegeGroup < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :user
  belongs_to :professorTitle
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/professor_title.rb
class ProfessorTitle < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/program_class.rb
class ProgramClass < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student_program.rb
class StudentProgram < ActiveRecord::Base
  belongs_to :student
  belongs_to :ProgramClass
  belongs_to :semester
  has_many :studentProgramCourses, foreign_key: "studentProgram_id"
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/student_program_professor.rb
class StudentProgramProfessor < ActiveRecord::Base
  belongs_to :studentProgram
  belongs_to :professor
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/university.rb
class University < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :userType
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :creator
  belongs_to :modifier
end

project/master-degree-system/app/controllers/student_program_professors_controller.rb
class StudentProgramProfessorsController < ApplicationController
  before_action :set_student_program_professor, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @student_program_professors = StudentProgramProfessor.all
    respond_with(@student_program_professors)
  end

  def show
    respond_with(@student_program_professor)
  end

  def new
    @student_program_professor = StudentProgramProfessor.new
    respond_with(@student_program_professor)
  end

  def edit
  end

  def create
    @student_program_professor = StudentProgramProfessor.new(student_program_professor_params)
    @student_program_professor.save
    respond_with(@student_program_professor)
  end

  def update
    @student_program_professor.update(student_program_professor_params)
    respond_with(@student_program_professor)
  end

  def destroy
    @student_program_professor.destroy
    respond_with(@student_program_professor)
  end

  private
    def set_student_program_professor
      @student_program_professor = StudentProgramProfessor.find(params[:id])
    end

    def student_program_professor_params
      params.require(:student_program_professor).permit(:studentProgram_id, :professor_id, :isPrimary, :isDefenseCommitee, :comment, :additionDate, :isAccepted, :acceptanceDate, :isExternal, :hasReceivedIndivdualReport, :hasReceivedCollectiveReport, :hasReceivedSatisfactionReport, :isCommitteeHead, :creator_id, :modifier_id)
    end
end

project/master-degree-system/app/helpers/courses_helper.rb
module CoursesHelper
end

project/master-degree-system/app/helpers/home_helper.rb
module HomeHelper
end

project/master-degree-system/app/helpers/roles_helper.rb
module RolesHelper
end

project/master-degree-system/app/helpers/student_program_professors_helper.rb
module StudentProgramProfessorsHelper
end

project/master-degree-system/app/helpers/users_helper.rb
module UsersHelper
end

project/master-degree-system/app/views/student_program_professors/_form.html.haml
= form_for(@student_program_professor) do |f|
  - if @student_program_professor.errors.any?
    #error_explanation
      %h2
        = pluralize(@student_program_professor.errors.count, "error")
        prohibited this student_program_professor from being saved:
      %ul
        - @student_program_professor.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.hidden_field :studentProgram_id, value: params[:student_program_id]
  .field
    = f.label :professor
    %br/
    = f.select :professor_id, Professor.includes(:user).map{|p| [p.user.name,p.id]}
  .field
    = f.label :is_Primary
    %br/
    = f.check_box :isPrimary
  .field
    = f.label :is_Defense_Commitee
    %br/
    = f.check_box :isDefenseCommitee
  .field
    = f.label :comment
    %br/
    = f.text_area :comment
  .field
    = f.label :addition_Date
    %br/
    = f.date_select :additionDate
  .field
    = f.label :is_Accepted
    %br/
    = f.check_box :isAccepted
  .field
    = f.label :acceptance_Date
    %br/
    = f.date_select :acceptanceDate
  .field
    = f.label :is_External
    %br/
    = f.check_box :isExternal
  .field
    = f.label :has_Received_Indivdual_Report
    %br/
    = f.check_box :hasReceivedIndivdualReport
  .field
    = f.label :has_Received_Collective_Report
    %br/
    = f.check_box :hasReceivedCollectiveReport
  .field
    = f.label :has_Received_Satisfaction_Report
    %br/
    = f.check_box :hasReceivedSatisfactionReport
  .field
    = f.label :is_Committee_Head
    %br/
    = f.check_box :isCommitteeHead
  .actions
    = f.submit

project/master-degree-system/app/views/student_program_professors/_index.html.haml
/ %h1 Listing student_program_professors
%h4 Supervisors
%table.table
  %thead
    %tr
      %th Professor
      %th Isprimary
      %th Additiondate
      %th Isexternal
      %th
      %th
      %th
  %tbody
    - @student_program_professors.where(isDefenseCommitee: false).each do |student_program_professor|
      %tr
        %td= student_program_professor.professor.user.name
        %td= student_program_professor.isPrimary
        %td= student_program_professor.additionDate
        %td= student_program_professor.isExternal
        %td= link_to 'Show', student_program_professor
        %td= link_to 'Edit', edit_student_program_professor_path(student_program_professor,student_program_id: @student_program.id)
        %td= link_to 'Delete', student_program_professor, method: :delete, data: { confirm: 'Are you sure?' }

%br
%h4 Commitee
%table.table
  %thead
    %tr
      %th Professor
      %th Isprimary
      %th Additiondate
      %th Isexternal
      %th
      %th
      %th
  %tbody
    - @student_program_professors.where(isDefenseCommitee: true).each do |student_program_professor|
      %tr
        %td= student_program_professor.professor.user.name
        %td= student_program_professor.isPrimary
        %td= student_program_professor.additionDate
        %td= student_program_professor.isExternal
        %td= link_to 'Show', student_program_professor
        %td= link_to 'Edit', edit_student_program_professor_path(student_program_professor,student_program_id: @student_program.id)
        %td= link_to 'Delete', student_program_professor, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'Add Professor', new_student_program_professor_path(student_program_id: @student_program.id)

project/master-degree-system/app/views/student_program_professors/edit.html.haml
%h1 Editing student_program_professor
= render 'form'
= link_to 'Show', @student_program_professor
/ = link_to 'Back', student_program_professors_path

project/master-degree-system/app/views/student_program_professors/new.html.haml
%h1 New student_program_professor
= render 'form'
/ = link_to 'Back', student_program_professors_path

project/master-degree-system/app/views/student_program_professors/show.html.haml
 
%p
  %strong Studentprogram:
  = @student_program_professor.studentProgram
%p
  %strong Professor:
  = @student_program_professor.professor
%p
  %strong Isprimary:
  = @student_program_professor.isPrimary
%p
  %strong Isdefensecommitee:
  = @student_program_professor.isDefenseCommitee
%p
  %strong Comment:
  = @student_program_professor.comment
%p
  %strong Additiondate:
  = @student_program_professor.additionDate
%p
  %strong Isaccepted:
  = @student_program_professor.isAccepted
%p
  %strong Acceptancedate:
  = @student_program_professor.acceptanceDate
%p
  %strong Isexternal:
  = @student_program_professor.isExternal
%p
  %strong Hasreceivedindivdualreport:
  = @student_program_professor.hasReceivedIndivdualReport
%p
  %strong Hasreceivedcollectivereport:
  = @student_program_professor.hasReceivedCollectiveReport
%p
  %strong Hasreceivedsatisfactionreport:
  = @student_program_professor.hasReceivedSatisfactionReport
%p
  %strong Iscommitteehead:
  = @student_program_professor.isCommitteeHead
%p
  %strong Creator:
  = @student_program_professor.creator
%p
  %strong Modifier:
  = @student_program_professor.modifier
= link_to 'Edit', edit_student_program_professor_path(@student_program_professor)
/ = link_to 'Back', student_program_professors_path